# Generated by Django 5.1.6 on 2025-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='preferred_area',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central'), ('all', 'All Areas')], default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='preferred_hours',
            field=models.CharField(choices=[('morning', '6 AM - 12 PM'), ('afternoon', '12 PM - 6 PM'), ('evening', '6 PM - 12 AM'), ('night', '12 AM - 6 AM'), ('flexible', 'Flexible')], default='flexible', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('cycle', 'Cycle'), ('auto', 'Auto')], default='bike', max_length=50),
        ),
    ]
