# Generated by Django 5.0.2 on 2025-03-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('customer_email', models.CharField(max_length=255)),
                ('restaurant_id', models.IntegerField()),
                ('restaurant_name', models.CharField(max_length=255)),
                ('table_number', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'joo_tablebooking',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
    ]
